language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - travis_retry pip install -r requirements-dev.txt

script:
  - py.test tests/ --cov=odinweb

after_success:
  - bash <(curl -s https://codecov.io/bash)
